🔀 :: (#10) button 구현
team-xquare/xquare-design-system-android pull request #14
Opened 2023-07-27 01:53 UTC by Tmdhoon2

### 개요

button design system 을 구현했습니다.

### 작업사항

- filled button, outlined button, text button background drawable 구현
- filled button, outlined button, text button button styles 구현
- button layout 구현
- XButton, XFloatingActionButton 커스텀뷰 클래스 구현
- XButton, XFloatingActionButton declared-styleable 선언
- filled button, outlined button, text button pressed selector 구현
- button layout image view, textview 간격 조절 용도 divider 구현

### 참고자료
- ripple effect https://ohdbjj.tistory.com/2
- view alpha https://hoyi327.tistory.com/65

2023-07-27 02:29 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +
상관없긴 한데, this가 필요할까요? XButton 스코프인건 확인할 수 있을 것 같아요(코드 수정 요구하는게 아니에요)

2023-07-27 02:31 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +) : LinearLayout(
혹시 LinearLayout에서 사용하는 기능이 있으신가요? Button은 ViewGroup이 아닌 View 아닌가요?

2023-07-27 02:34 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +) : LinearLayout(
AppCompatButton을 상속하게 만들어주시면 좋을 것 같아요

2023-07-27 02:37 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +    }
음.. 개인적인 생각인데 여기는 View Controller처럼 다른 코드들이 많이 존재하지 않아서, 함수 분리가 필요 없을 것 같아요. 그리고 생성자와 init 블럭 사이가 분리되어있어서 한 눈에 보기 조금 어려운 것 같다는 생각이 들어요. 생성자도 여러개 생길 수 있으니, 클래스 body 내에 생성자를 선언해주시면 안될까요?

2023-07-27 02:37 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +    context: Context,
context도 null 가능하게 만들어주세요

2023-07-27 02:38 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +    }
변수명이 어떤걸 의미하는지 잘 모르겠어요.

2023-07-27 02:39 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +    }
변수명이 어떤걸 의미하는지 잘 모르겠어요.

2023-07-27 02:40 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +        )
AppCompatButton을 상속하도록 만들면 inflater 코드도 최소화할 수 있는 것 같아요.

2023-07-27 02:41 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +) : LinearLayout(
https://velog.io/@tjeong/Android-%EC%A0%9C%ED%8A%B8%ED%8C%A9-1-androidx-%EC%99%80-appcompat 
AppCompat에 관한 설명이에요

2023-07-27 02:43 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +    }
함수를 분리한다는 점에서 좋은 것 같기는 하지만, 함수 내부 동작들이 대부분 한두 줄정도 되고, 버튼 클래스 멤버 함수 이름과 동일한 다른 구성요소 함수 호출로 이루어져 있어서 너무 세분화된 것 같다고 생각됩니다.

2023-07-27 02:43 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +        if (text == null) textView.visibility = View.GONE
ktlint 확인하셨나요?

2023-07-27 02:43 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +            )
```suggestion
                R.styleable.XButton_textColor,
                resources.getColor(R.color.black),
            ),
```

2023-07-27 02:44 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +            )
아님 아예 한 줄로 두셔도 될 것 같습니다

2023-07-27 02:44 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +            )
if 조건문 안에 들어가는 boolean 값 변수로 새로 만들어주세요

2023-07-27 02:45 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +    private fun setEnabled() {
`setEnabled()`라는 네이밍은 컴포넌트를 활성화한다는 의미로 생각됩니다.

2023-07-27 02:46 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +            alpha = 0.4f
`0.4f` 는 다른 컴포넌트들에서도 중복되는 코드일 것 같아요.

2023-07-27 02:46 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_button_floating.xml
어떤 컴포넌트인가요?

2023-07-27 02:47 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_button_filled.xml
filled는 여러 상태가 있을 것 같은데, 너무 추상화된 것 같습니다. 색상으로 보니 enabled 상태인것 같은데, 네이밍에 명시 부탁드립니다

2023-07-27 02:48 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_button_outlined.xml
> +        android:width="1dp"
이것도 공통적으로 사용되도록 관리할 수 있을 것 같네요.

2023-07-27 03:20 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/divider.xml
어떤 divider인가요?

2023-07-27 03:21 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/selector_button_outlined.xml
outlined button의 어떤 셀렉터인가요?

2023-07-27 03:21 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/selector_button_text.xml
text button의 어떤 selector인가요?

2023-07-27 03:22 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/selector_button_outlined.xml
text가 될 수도 있고, text color, elevation이 될 수도 있고, background가 될 수도 있을 것 같습니다.

2023-07-27 03:23 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button.xml
> +            android:layout_height="24dp"
많은 부분에서 재사용되는 코드여서, 상수로 준 값들 다 dimen으로 관리할 수 있을 것 같아요.

2023-07-27 03:24 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button.xml
> +            android:id="@+id/iv_xbutton"
이 네이밍은 이렇게 하실건가요..? `image`로 하기로 되지 않았었나요?

2023-07-27 03:24 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button.xml
> +            android:id="@+id/iv_xbutton"
그리고 view binding 사용을 지양하기로 했으니, 전역 네임스페이스가 오염되지 않게 어느 레이아웃의 어느 컴포넌트 아이디인지 네이밍에서 알 수 있도록 해주세요

2023-07-27 03:25 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button.xml
> +            android:id="@+id/iv_xbutton"
(만약 AppCompatButton을 상속하게 만들면 필요없어질 **수**도 있을 듯 하네요.)

2023-07-27 03:25 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button.xml
> +            android:layout_height="wrap_content" />
이 텍스트 스타일도 버튼 태그로 받을 수 있겠죠?

2023-07-27 03:26 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button.xml
> +        android:showDividers="middle">
gravity가 명시되어있었으면 좋겠어요. 아예 component 담고 있는 view group은 style로 지정해두셔도 깔끔할 것 같고요.

2023-07-27 03:27 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button.xml
> +            android:id="@+id/tv_xbutton"
xbutton보다는 그냥 button이 나을 것 같네요.

2023-07-27 03:29 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button_floating.xml
Floating 버튼이 아니라 Floating Action Button인 것 같네요. 머티리얼 디자인에 있는 버튼 상태들 중 떠있는 상태가, 우리의 floating 이라는 네이밍이랑 겹칠 수도 있을 것 같아요.
<img width="871" alt="image" src="https://github.com/team-xquare/xquare-design-system-android/assets/101160207/00e13da5-a118-4d71-b170-3d4f905bf96d">

2023-07-27 03:33 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button_floating.xml
> +
디자인시스템에 floating text button 추가되었습니다. 확인하시고 추가 부탁드릴게요

2023-07-27 03:35 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/button_floating.xml
> +            android:contentDescription="Floating Button Icon" />
솔직히 여기 description이 필요할지 잘 모르겠습니다. 만약 접근성을 위해서라면 button 자체에 포커스가 잡히도록 해야할 것 같아요.

2023-07-27 03:36 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textColor" format="integer"/>
혹시 이건 `android` 네임스페이스에 없는 속성인가요?

2023-07-27 03:36 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:background" format="reference|integer"/>
background drawable을 받는건가요, color res를 받는건가요?

2023-07-27 03:36 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:src" format="reference|integer"/>
src는 background src인가요, icon src인가요?

2023-07-27 03:37 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +
확인했습니당

2023-07-27 03:37 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:text" format="string|integer"/>
icon tint 속성은 없나요? 이외에도 많은 속성들이 더 필요할 것 같아요

2023-07-27 03:56 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +        <item name="textColor">@color/on_primary</item>
`android` 네임스페이스에 없나요?

2023-07-27 04:03 UTC, JunJaBoy commented
1. 네이밍이 부적절하다고 느껴짐
    - 커스텀 뷰 클래스 함수
    - drawable 네이밍
        - bg_button_filled -> 어떤 상태인지 파악이 어려움
2. 디자인시스템 컴포넌트의 유연함이 부족함
    - 뷰를 재활용의 어려움
        - 클래스 변수명의 의미를 파악하기 어려움
        - Button임에도 LinearLayout을 상속하고 있음
        - 상황에 따라 아이콘, 텍스트 등을 사용하지 않을 수 있지만 구현되지 않은 부분도 있음(드랍다운 등)
    - 하드코딩된 값들
        - stroke, alpha 등등

2023-08-02 09:40 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/button/XButton.kt
> +    context: Context,
혹시 이유가 있을까요?? AppCompatButton 내부 생성자도 Context 는 NonNull 로 선언되어 있기도 하고..

2023-08-02 15:44 UTC, chlgkdms commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
> +    const val ButtonDisabled = 0.4f
변수 네이밍이 파스칼 케이스네요..

2023-08-03 02:05 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
> +    const val ButtonDisabled = 0.4f
음 object 안 상수값들은 원래 파스칼 케이스로 짓지 않나요??..

2023-08-03 10:30 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
> +    const val ButtonDisabled = 0.4f
보통 upper snake case로 짓죠? pascal case DMS때 Jetpack Compose 라이브러리에서 제공하는 확장 프로퍼티 등에서 사용되는 변수명과 통일시키기 위해 임의로 정했던 규칙으로 기억합니다(저는 이때 upper snake case 사용을 주장했었고요). 그리고 object 안의 상수값이라고 하기보다는 모든 상수 네이밍에 해당되는 규칙일 것 같아요.

2023-08-03 10:36 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    ) {
개인적으로 클래스 자신을 호출하는 패턴이 더 좋은 코드 같습니다. 최소의 파라미터를 가지고 있고, 파라미터의 타입이 모두 다른 생성자가 아니라면 상위 클래스의 생성자를 호출하는 대신, 파라미터가 보다 적은 자신의 생성자를 호출하는게 코드상으로 더 깔끔하다는 느낌이 들어요.
https://shinjekim.github.io/kotlin/2019/09/02/Kotlin-코틀린의-생성자(Constructor)/

2023-08-03 10:38 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        )
정말 개인적인 의견이고, 저도 승훈님이 작성하신 코드처럼 작성할 것 같긴 한데, 이런 곳에 사용되는 네임드 아규먼트는 불필요하다고 느껴져요. 어떻게 생각하시나요? @team-xquare/android

2023-08-03 10:39 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        )
줄바꿈 없으면 린트 오류가 발생하나요? 네임드 아규먼트를 사용하는 것도 아니고, 아규먼트의 이름이 긴 것도 아니어서 불필요한 줄바꿈같습니다.

2023-08-03 10:39 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        )
뭐 누가 린트 만들어주겠죠? 🤓

2023-08-03 10:40 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    }
요건 추상화 가능하지 않을까요?

2023-08-03 10:42 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            )
요기도 오히려 줄 바꿈이 많아서 눈의 피로가 올라갈 수도 있다고 해야할까요? 인텔리제이에서는 아규먼트 이름들 다 보여줘서 상관없다고 해도, 어차피 깃헙이나 형상관리 툴에서는 그냥 코드만 보이기때문에 한 줄로 가도 상관없다는 입장입니다 ㅇㅅㅇ

2023-08-03 10:42 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        ) {
??????? 이 코드 줄바꿈이 예술적인데요

2023-08-03 10:43 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        ) {
가독성을 위해 따로 변수로 빼는걸 추천드립니다 👍

2023-08-03 10:44 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +    private fun setEnabled() {
얼핏 봤을때는 '버튼을 활성화한다'는 의미로 보여요. 다른 함수명이 없을까요?

2023-08-03 10:56 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
> +    const val ButtonDisabled = 0.4f
아하 확인했습니당

2023-08-03 10:56 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    ) {
옹 참고해보겠습니당

2023-08-03 10:58 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    }
XButton 이랑 XIconButton 에서 추상화 가능할 것 같네요!

2023-08-03 10:58 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        ) {
아하 좋은 의견 감사합니당

2023-08-03 10:59 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +    private fun setEnabled() {
아 XButton 이랑 네이밍 맞춘다는게 깜빡했네요... 위에 남겨주신 코멘트처럼 이 부분도 추상화 가능할 것 같습니다

2023-08-03 11:48 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    private fun setSrc() {
setSrc, setBackground같은 함수는 인터페이스로 추상화하면 어떨까요? 
https://developer.android.com/reference/android/widget/Checkable
https://developer.android.com/reference/androidx/core/view/TintableBackgroundView

2023-08-03 11:57 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    private fun setSrc() {
그리고 내부적으로 leading src와 trailing src를 설정하는 함수를 따로 호출하는 구조로 분리하면 좋겠어요.

2023-08-03 12:00 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +        ) {
요기도 변수로 따로 빼면 좋을 것 같아요

2023-08-03 12:04 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            )
그리고 이 코드는 `leadingSrc = attributes.getDrawable(...).apply { setBounds(...) }` 이렇게 작성하면 어떨까요? 🍎 이렇게 작성하면
- 가독성 향상
- 라인 수 감소
- null 값일 수도 있다는 것을 변수 선언하면서 인지
  - 밑에 `leadingSrc?.run` 코드에서 leadingSrc가 null 가능하다는 것을 다시 꺠달음
등의 이점이 있을 수 있겠다고 생각합니다. 승훈님이 이렇게 작성하신 이유가 따로 있을까요?

2023-08-03 12:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_button_outlined_enabled.xml
> +        android:width="1dp"
요것도 회의 통해서 공통 dimen으로 정의 부탁드려요!

2023-08-03 12:12 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/divider_horizontal_8dp.xml
dp도 네이밍에 포함시켜줘야할까요? 어차피 컴포넌트는 다 dp 써서 필요없다는 생각입니다..

2023-08-03 12:12 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/divider_horizontal_8dp.xml
그리고 이 divider는 어떤 역할을 하는지 이름에 포함되어야할 것 같아요

2023-08-03 12:13 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/ic_test_24dp.xml
아이콘은 사용할 때 ImageView 크기에 따라서 크기가 달라지기때문에 크기 명시가 필요 없을 것 같아요. 혹시 아이콘에 크기를 넣어주신 이유가 있으신가요?

2023-08-03 12:15 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/button_padding.xml
> +    <dimen name="button_padding_large">16dp</dimen>
button이기 이전에 padding이지 않나요? 저는 `padding_button~`이 더 올바른 네이밍이라고 생각합니다.

2023-08-03 12:17 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/button_padding.xml
이 파일은 `button_padding`보다 `dimens_button`으로 두어서 margin, corner 등의 값들도 여기에 정의할 수 있도록 하면 어떨까요?

2023-08-03 12:18 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    </style>
사실 FloatingActionButton은 Button과 분리해야한다는 입장.. 그리고 FAB에 텍스트도 입력할 수 있도록 작성하셨나요?

2023-08-03 12:19 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    ) {
나중에 결과 알려주세요~

2023-08-03 13:13 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_button_outlined_enabled.xml
> +        android:color="@color/primary" />
요거 primary 고정값 사용하실건가요? dynamic colors 지원을 위해서는 ?attrs로 참조하셔야할 것 같아요

2023-08-03 15:36 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    ) {
위 글 읽어봤는데 this로 호출하는 방식이 더 좋은 것 같다고 생각이 드네용
클래스 생성을 생성자 하나가 담당한다는 느낌이 들어서(?)

2023-08-03 15:45 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/typography/XdsTextView.kt
좋을 것 같아요!

2023-08-03 16:23 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/drawable/bg_button_outlined_enabled.xml
> +        android:color="@color/primary" />
앗 아직 리베이스를 안했었네용

2023-08-04 06:36 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    }
으음 근데 XButton 은 AppCompatButton 상속이고, XIconButton 은 AppCompatImageButton 상속인데 인터페이스에 함수 정의하는 방식 말고 추상화가 가능한가요??..

2023-08-04 09:17 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
> +package com.xquare.xdsandroid
알파는 버튼에만 해당되는 사항이 아닌 것 같은데, 공통 속성으로 만들면 어떨까요?

2023-08-04 09:17 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        )
문서로 정리되어있긴 해요. 단순하게 ktlint에서 오류를 표시하지 않는다면 통과하는 정도로 작성해두었는데, 문서 참고하시면 어떤 사항에 해당되어서 제가 말씀드리는지 이해하실 수 있을 것 같아용

2023-08-04 10:20 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        )
원소 이름이 단순한 경우에 해당되는걸까요??

2023-08-07 11:33 UTC, yeon0821 approved these changes

2023-08-09 08:31 UTC, rladmsdh commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            val trailingHint =
hint -> tint 오타 있어요

2023-08-09 09:18 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    public constructor(context: Context) : this(context, null) {
바디 삭제 부탁드립니다~

2023-08-09 09:19 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    }
공통 속성으로 뺄 수 있을 듯 ㅇㅇ

2023-08-09 09:23 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    private fun setButtonEnabled() {
`setIsEnabled`?

2023-08-09 09:23 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    private fun setButtonEnabled() {
or `setWhetherEnabled1

2023-08-09 09:24 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +    }
여기도 블록 제거해주세요

2023-08-09 09:31 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/dimens_button.xml
> +    <dimen name="stroke_button_width_xsmall">1dp</dimen>
주석이랑 태그 사이에 줄바꿈이 있어요

2023-08-09 09:33 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +        <item name="trailingTint">?attr/colorOnPrimary</item>
src/icon 들어가는게 좋을 것 같습니다

2023-08-09 14:28 UTC, rladmsdh commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        setAttrs()
여기에 attributes.recycle() 이 코드를 추가해서 garbage collection을 해제시킬 수 있다고 합니다.
https://mashup-android.vercel.app/mashup-10th/dahyun/customview/customview/
이거 참고하시면 좋을것 같아요

2023-08-09 14:28 UTC, rladmsdh commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +        setAttrs()
이것도

2023-08-09 14:32 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        setAttrs()
이런 리뷰 완전 좋습니다

2023-08-10 05:41 UTC, JunJaBoy requested changes

2023-08-10 06:24 UTC, rladmsdh approved these changes

2023-08-10 11:38 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        setTextAppearance(R.style.BodyLarge)
넵 textAppearance 속성으로 받을 수 있을 것 같아요

2023-08-11 02:47 UTC, Tmdhoon2 commented
@JunJaBoy 네이밍 좀 도와주실 수 있나요...??

2023-08-11 03:17 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/ButtonBase.kt
> +package com.xquare.xdsandroid.button
다른 뷰 클래스에도 적용할 수 있는 함수들같은데, 단위를 버튼보다 크게 잡으면 어떨까요?

2023-08-11 03:18 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        setTextAppearance(R.style.BodyLarge)
커스텀뷰 태그로 받을 수 있다는 말씀이신거죠?

2023-08-11 03:19 UTC, JunJaBoy reviewed
.

2023-08-11 04:38 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        setTextAppearance(R.style.BodyLarge)
<img width="476" alt="스크린샷 2023-08-11 오후 1 38 37" src="https://github.com/team-xquare/xquare-design-system-android/assets/102812085/bb94d67a-6f39-46da-b712-8c249728a33e">

위의 태그 이용하면 가능합니당

2023-08-11 06:10 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewBase.kt
보통 ~Base 대신, Base~라고 하지 않나용? 그리고 `initView()`에서 `setAttrs()`, `setIsEnabled()`를 무조건 호출하니까, default 메서드로 만들어서 하위 클래스에서 구현을 강제하지 않아도 될 것 같아요

2023-08-11 06:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/CustomViewProperties.kt
지금 이 방법 괜찮아보여요 🌟 그런데 혹시 컴포넌트가 더더욱 많아진다면 속성별로 구분을 어떻게 해야할까요? ex) 버튼 속성과 텍스트 속성 등등

2023-08-11 06:12 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
> +}
접근제한자 명시해주시면 좋을 것 같아요. 그리고 이건 디자인시스템 내부적으로 활용해야만 할 것 같은데, 어떻게 생각하시나요??

2023-08-11 06:12 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/CustomViewProperties.kt
+ 위 클래스 커멘트 보시고 접근제한자 신중하게 고려해주세요!

2023-08-11 06:15 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewImage.kt
> +    fun setTrailingSrc()
leading과 trailing을 지정해주지 않는 클래스를 위해서 요건 다른 곳에 만들면 어떨까요?

2023-08-11 06:18 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +public class XButton : AppCompatButton, CustomViewBase, CustomViewText, CustomViewImage {
혹시 AppCompatButton은 클래스가 아닌가요? (constructor invocation이 없습니다..?)

2023-08-11 06:19 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    private var trailingSrc: Drawable? = null
밑에 코드를 쭉 봤는데, 요걸 변수로 두지 않고도 구현할 수 있을 것 같더라고요.

2023-08-11 06:19 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    private var trailingSrc: Drawable? = null
이 변수는 AppCompat 클래스 내부 깊은 곳에 또 저장될거고, 처음 버튼을 초기화한 뒤 사용할 일이 크게 없을 것 같다는 생각이 들었어요.

2023-08-11 06:20 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +    private var src: Drawable? = null
여기도 변수 사용 안하면 어떨까요?? 222

2023-08-11 06:22 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +    }
엥 요 안에서 alpha, isEnabled 이런 곳에 대입되는 친구들을 기본값을 만들라는게 아니라, 이 버튼 클래스보다 더 추상화된 상위 클래스에서 정의해줄 수 있게 하면 어떨까 하는 말이었어요. ex) `override fun setEnabled(enabled: Boolean) { super.setEnabled(enabled) }`처럼 호출할 수 있게

2023-08-11 06:23 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +    }
(물론 boolean값은 attr에서 받아주는걸로)

2023-08-11 06:24 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:textColor" format="reference|integer"/>
src 사이즈, font family같은 속성들도 받으면 좋을 것 같아요

2023-08-11 06:24 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:tint" format="color" />
여기도 src 사이즈 받을 수 있으면 좋겠습니다

2023-08-11 06:25 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/dimens_button.xml
> +    <dimen name="padding_button_large">16dp</dimen>
```suggestion
    <!--Padding-->
    <dimen name="padding_button_small">8dp</dimen>
    <dimen name="padding_button_medium">12dp</dimen>
    <dimen name="padding_button_large">16dp</dimen>
```

2023-08-11 06:25 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/dimens_button.xml
> +    <dimen name="stroke_button_width_xsmall">1dp</dimen>
```suggestion
    <!--stroke width-->
    <dimen name="stroke_button_width_xsmall">1dp</dimen>
```

2023-08-11 06:26 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/dimens_button.xml
> +    <dimen name="stroke_button_width_xsmall">1dp</dimen>
그리고 stroke width라는게 붙어있어야 하는 개념이어서 `stroke_width_button_xsmall`이라고 명명하면 좋을 것 같은데, 어떻게 생각하세요?

2023-08-11 06:28 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +        <item name="android:paddingBottom">@dimen/padding_button_medium</item>
이 패딩 값들은 버튼에만 들어가는게 아니긴 한데, 디자인 시스템에 있는 grid 크기별로 패딩을 만들어서 @dimen/padding_4 요렇게주면 안될까요? 그럼 패딩 하나 수정되면 모든 컴포넌트에 공통으로 적용되서 좋을 것 같아요

2023-08-11 06:29 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:tint" format="color" />
그리고 text style은 어떻게 주나요?

2023-08-11 06:30 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    </style>
src 사이즈도 기본으로 가지고있으면 좋을 것 같아요

2023-08-11 06:30 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +        <item name="android:background">@drawable/bg_button_outlined_enabled</item>
selector가 아닌 이유가 있나요?

2023-08-11 06:31 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
alpha는 버튼에만 해당되는 값이 아닌 것 같아요.

2023-08-11 06:32 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ButtonConstants.kt
internal하게 `DesignSystemDefaults`라고 지으면 어떨까요?

2023-08-11 06:37 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewBase.kt
`BaseView` 좋을 것 같아요

2023-08-11 06:40 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewImage.kt
> +    ): Int
요건 속성에 접근하는 메서드 한 줄 호출하는 것 같은데, 추상화할 필요가 없을 것 같아요. 또, 이 코드가 필요 없는 뷰가 있을 수도 있을 것 같아요

2023-08-11 06:42 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewBase.kt
+ 개인적으로 함수 분리해서 가독성 높이는 건 좋은데, 꼭 필요한 작업인가 하는 의문이 계속 있었어요. 유지보수할 때 새로 투입된 인원들이 읽기는 편하지만, 어떻게 함수를 분리하고 사용하는지에서 막막할 것 같다는 생각에 그냥 생성자에서 모든 작업을 처리해도 되지 않을까라는 의견도 있습니다.

2023-08-11 06:43 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewImage.kt
이 클래스가 필요한지 잘 모르겠습니다. 차라리 leading, trailing src를 설정하는 부분을 추상화하면 좋을 것 같아요. `LeadingDrawable`, `TrailingDrawable`이라는 클래스 따로따로 나눠서..

2023-08-11 06:43 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewImage.kt
그런데 또 이 함수도 분리할 필요가 있을까요..?

2023-08-11 06:45 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewText.kt
`Typable` 어떠신가요?

2023-08-11 06:47 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +                intrinsicHeight,
다른 스코프함수 써서 리시버 이름 달아주시면 좋을 것 같아요. XButton 멤버인 줄 알고 계속 찾아봤네요..

2023-08-11 06:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    }
전에 말씀드렸던 것 같은데, optional한 leading src와 trailing src를 받아서 `if (leading != null) setLeadingSrc()` 이렇게 만들어주시면 좋을 것 같아요. 그리고 `setLeadingSrc()`, `setTrailingSrc()` 내부에서 XButton 멤버인 leadingSrc, trailingSrc 값을 재정의해주는 것보다, 두 함수들을 src를 반환하는 `get~()` 함수로 만들고, `setDrawableAttrs()`함수 내에서 `val leadingSrc = getLeadingSrc()`, `val trailingSrc = getTrailingSrc()` 변수를 만들어준 뒤에 `setCompoundDrawables()`함수에 nullable한 상태 그대로 넣어주는게 언어적으로, 시각적으로 더 이해가 잘되는 패턴같다고 생각합니다.

2023-08-11 06:51 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    }
처음 코드를 보고 흐름을 가늠하기 어려워서 수정 제안드립니다.

2023-08-11 07:32 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/CustomViewProperties.kt
전에 속성들을 오브젝트로 관리하면 좋을 것 같다는 의견으 제시해주셔서 반영했습니다!

2023-08-11 07:34 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/CustomViewProperties.kt
아.. 그랬었군요.. 번거로운 작업 만들어서 죄송합니다 ㅠ

2023-08-11 07:36 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/CustomViewProperties.kt
제가 저번에 말씀드릴 때 생각이 정확하게 기억나진 않습니다만.. 이번에 리뷰하면서 클래스 추상화를 통해서 해결 가능한 문제라고 생각되었어요

2023-08-11 07:51 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +public class XButton : AppCompatButton, CustomViewBase, CustomViewText, CustomViewImage {
아 밑에서 constructor로 생성자 정의해줘서 그렇습니당

2023-08-12 01:52 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/CustomViewImage.kt
> +    fun setTrailingSrc()
엇 혹시 생각나는 방법 있으시면 공유 부탁드립니당

2023-08-12 03:43 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:tint" format="color" />
아이콘 버튼은 text 속성이 없어서 textStyle이 필요없지 않나요??

2023-08-12 03:57 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +        <item name="android:background">@drawable/bg_button_outlined_enabled</item>
selector로 ripple color를 구현하는 방법을 button drawable 자체에 ripple color를 주는 방법으로 변경해서 selector를 제거했습니당

2023-08-12 09:37 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    </style>
src 사이즈는 dp 값이 아닌 int 값으로 받아도 괜찮을까요??

2023-08-13 07:10 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    private lateinit var attributes: TypedArray
이것도 모든 뷰마다 가지고있는 속성같은데 추상화 가능할까요? 밑에서 은오님이 말씀하신 `.recycle()` 함수도 상위 클래스에서 호출하면 될 것 같아요.

2023-08-13 07:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            ),
이건 변수로 따로 빼면 가독성이 향상될 것 같아요.

2023-08-13 07:12 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +                R.styleable.XButton_android_enabled,
enabled 속성은 모든 뷰에 있지 않나요..? button에만 존재하는 속성같은 느낌이 드는데, 혹시 style도 추상화가 가능할까요?

2023-08-13 07:14 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            )
이 코드가 getLeadingSrc()에는 없는데 어떤 차이가 있나요?

2023-08-13 07:15 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/Typable.kt
접근제한자 명시해주세요

2023-08-13 07:16 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableView.kt
여기 접근제한자 명시해주세요. xds 외적으로 뷰를 만들 수 있도록 허용해주는건 디자인시스템 업데이트를 지양하게 만들 것 같습니다.

2023-08-13 07:16 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableDrawable.kt
접근제한자 명시해주세요

2023-08-13 07:19 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableDrawable.kt
네이밍이 drawable 하나만 지정해줄 수 있는 것 같지만, 실제로는 leading과 trailing을 지정해주는 메서드를 가지고 있네요. 만약 top과 bottom에도 drawable을 지정해줄 수 있도록 해야한다면 어떻게 할까요? leading과 trailing drawable은 각각 LeadingDrawable, TrailingDrawable 인터페이스 두 개로 나누면 좋을 것 같습니다.

2023-08-13 07:19 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/ViewDefaults.kt
접근제한자 명시해주세요

2023-08-13 07:21 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +    private lateinit var attributes: TypedArray
attributes는 상위 뷰에서도 가지고 있는 속성이니, 단순하게 초기화하는 함수 사이에 파라미터와 아규먼트로만 쓰게 해서 메모리 낭비를 방지할 수 있을 것 같아요.

2023-08-13 07:22 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableDrawable.kt
내부 함수들이 public함수로 열려있어서, 다른 컴포넌트에서 얼마든지 View의 초기화 메서드에 접근할 수 있네요. 내부 함수들까지 접근제한자 명시해주세요

2023-08-13 07:24 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_button_outlined_enabled.xml
> +            <solid android:color="?attr/colorOnPrimary" />
outlined 버튼은 fill이 없어요.

2023-08-13 07:27 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_button_outlined_enabled.xml
> +        <inset android:inset="@dimen/stroke_width_1">
inset은 뭔가요?

2023-08-13 07:29 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:tint" format="color" />
혹시 지금 시점에서 사이즈 지정하는 동작 클래스 내부에 존재하나요?

2023-08-13 07:30 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:tint" format="color" />
\+ layotu_width, height 등의 속성과 같은 값을 받았으면 합니다. 혹시 두 개도 format이 integer일까요?

2023-08-13 07:31 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    <style name="FilledButton" parent="XButton">
여기 버튼 이름에 X 포함 안해주신 것 같습니다

2023-08-13 07:32 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
버튼 이름들에 X 넣어서 다른 라이브러리 구성요소와 구별할 수 있도록 해주시면 좋을 것 같아요

2023-08-13 07:33 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    </style>
int로 받으시려는 이유가 있나요?

2023-08-13 07:37 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    </style>
음 보니까 이게 다른 버튼들 상위 태그 개념이었네요. 그렇다면 기반이라는 걸 이름에 명시하기 위해서 BaseXButton 이렇게 지어도 괜찮을 것 같습니다

2023-08-13 07:37 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/dimens_padding.xml
> +    <dimen name="stroke_width_1">1dp</dimen>
```suggestion
    <!--padding-->
    <dimen name="padding_8">8dp</dimen>
    <dimen name="padding_12">12dp</dimen>
    <dimen name="padding_16">16dp</dimen>

    <!--stroke width-->
    <dimen name="stroke_width_1">1dp</dimen>
```

2023-08-13 09:23 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    </style>
아 dp 값으로 받을 수가 있네용 없는 줄 알고 int로 받아서 dp로 바꿔야 하나 해서 여쭤봤습니당

2023-08-13 09:24 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    }
이 부분 수정했는데 확인하셨나요??

2023-08-13 12:07 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            )
아하 icon color 지정하는 코드인데 작업하다가 빼놓은것 같습니다

2023-08-13 13:08 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/drawable/bg_button_outlined_enabled.xml
> +        <inset android:inset="@dimen/stroke_width_1">
drawable 내부에 padding을 주는 속성인데, ripple 효과가 stroke를 침범해서 색이 겹치길래 적용해 주었습니당

2023-08-13 14:55 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableDrawable.kt
인터페이스 내부 함수는 body 선언 했을 때 private만 가능하지 않나요??

2023-08-14 01:17 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +                R.styleable.XButton_android_enabled,
혹시 attrs.xml 에 정의되어 있는 style 추상화를 말씀하시는건가요??

2023-08-14 10:17 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/TrailingDrawable.kt
여기도 접근제한자 붙여주세요

2023-08-14 10:18 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/Typable.kt
> +        includeFontPadding: Boolean,
text 제외한 파라미터에 기본값 넣어줘도 괜찮을 것 같아요

2023-08-14 10:19 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        )
이 함수 인자 변수로 따로 만들어주실 수 있나요? default~ 붙이면 가독성이 좋을 것 같다고 생각했어요

2023-08-14 10:20 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            )
요기 아규먼트들도 변수 선언해주시면 어떨까요? 가독성이 좋아질 것 같아요 22

2023-08-14 10:20 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            )
요기들도요

2023-08-14 10:21 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +            )
혹시 이 틴트도 따로 변수로 만들어주실 수 있나요?

2023-08-14 10:22 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +        }
여기도 긴 아규먼트들 따로 변수 만들어주면 어떨까요?

2023-08-14 10:22 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +                    R.styleable.XIconButton_android_tint,
같은 값을 두 번 입력해주는 이유가 무엇인지 궁금해요(진짜 모름)

2023-08-14 10:22 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +                    R.styleable.XIconButton_android_tint,
희망 값과 기본 값인가요?

2023-08-14 10:24 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +    <style name="XFilledButton" parent="BaseXButton">
엥 이름 앞에 붙이는 것보다는 FilledXButton 이런게 낫지 않을까 하는 개인적인 생각입니다

2023-08-14 10:24 UTC, JunJaBoy reviewed
수고하셨습니다. 한 번만 더 확인해주세요

2023-08-14 14:06 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +                    R.styleable.XIconButton_android_tint,
첫 번째 인자로 전달된 값이 없는 경우에 두 번째 인자인 default 값을 반환하는 형식인데 두 번째 참조가 잘못 들어간 것 같습니당

2023-08-15 05:11 UTC, JunJaBoy reviewed
찐막

2023-08-15 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +            DrawableCompat.wrap(this).setTint(srcTint)
요기도 스코프 붙여주세요

2023-08-15 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textStyle" format="reference" />
안드로이드 네임스페이스에는 없는 속성인가요?

2023-08-15 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
>      <declare-styleable name="XdsTextView">
이제 확인한건데 Textfield가 아니네요. 그리고 Xds라고 명명해두신 것 같아요

2023-08-15 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
이 네이밍은 지금 당장은 괜찮은데, 나중에 버튼이 추가될 때마다 더 개선해봐야할 것 같습니다.

2023-08-15 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
>      <declare-styleable name="XdsTextView">
이 부분은 연우님 관할이라면 수정하지 않으셔도 될 것 같아요

2023-08-15 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +            alpha = ViewDefaults.VIEW_DISABLED
만약 alpha가 뷰 멤버라면 나중에 View 확장함수로 `View.disable(aplha: Float = ViewDefaults.VIEW_DISABLED) {}` 요렇게 두셔도 될듯

2023-08-15 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +            alpha = ViewDefaults.VIEW_DISABLED
\+ VIEW_DISABLED보다는 ALPHA_DISABLED가 더 좋은 네이밍같다고 생각됩니다

2023-08-15 05:37 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        includeFontPadding: Boolean,
넵 그렇습니당

2023-08-15 05:56 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/styles_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
좋습니당

2023-08-15 07:21 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textStyle" format="reference" />
있는 속성이긴 한데 원래 textAppearance랑은 내부 구현이 조금 다릅니다.
textAppearance 라는 속성은 styles.xml에서 정의한 font style들을 적용할 수 있는데, android 네임스페이스의 textStyle 같은 경우는 int 값으로 단순히 font weight만 조절이 가능합니다.

원래는 android:textAppearance 속성을 사용했는데 이걸 실제 개발에서 사용할 때, 속성 이름이 조금 헷갈릴 수 있을 것 같아 이렇게 작업했습니다.

2023-08-15 07:38 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +            ),
요거 변수로 선언해주면 어떨까요?

2023-08-15 07:38 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textStyle" format="reference" />
엥 그럼 헷갈리지 않도록 텍스트 모양을 appearence, 폰트 웨이트를 textstyle로 두어야하는거 아닌가요?

2023-08-15 08:35 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textStyle" format="reference" />
으음 근데 android:textStyle 속성은 textAppearance가 적용되어 있는 상태에서는 동작하지 않는 것 같아요
그럼 텍스트의 모양을 정하는 속성 이름은 textAppearnce나 textStyle중 어떤게 더 적합할까요??

2023-08-15 08:37 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/attrs.xml
>      <declare-styleable name="XdsTextView">
어차피 deprecated 된 컴포넌트라서 이 부분은 추후에 삭제하면 괜찮을 것 같습니다

2023-08-15 08:41 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textStyle" format="reference" />
음.. body, title 등의 모양을 지정하는 건 textAppearence로 지정하고, 텍스트 두께, 기울기 등은 textStyle로 지정해주는게 좋을 것 같아요. 안드로이드 네임스페이스 사용해서 가능할까요?

2023-08-15 08:41 UTC, JunJaBoy reviewed
.

2023-08-15 10:45 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textStyle" format="reference" />
넵 가능할 것 같습니다!

2023-08-16 09:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableView.kt
> +    fun View.setIsEnabled(alpha: Float = ViewDefaults.ALPHA_DISABLED)
이것도 initview에서 호출해줄 수 있으면 좋겠어요

2023-08-16 09:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableView.kt
> +    fun View.setIsEnabled(alpha: Float = ViewDefaults.ALPHA_DISABLED)
\+ 이 클래스 밖에 확장함수를 만들고, 그 확장함수를 호출하는 래핑 함수를 만들면 좋겠다는 뜻이었어요. 그 래핑 함수는 파라미터로 아무것도 받지 않으면 좋을 것 같습니다.

2023-08-16 09:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +    override lateinit var attributes: TypedArray
이 코드 없앨 수 있을 것 같은데,, 스크린샷해서 이슈 남겨주세요

2023-08-16 09:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        typeface = textStyle
코드 중복이 있는 것 같아요

2023-08-16 09:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        }
알파만 바꿔주나요? 뷰랑 상호작용할 수 없게 만들어주어야하는 거 아닌가요?

2023-08-16 09:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +            DrawableCompat.wrap(this).setTint(srcTint)
여기 레이블 붙여주실 수 있나요?

2023-08-16 09:50 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
> +            setImageDrawable(this)
여기도 레이블 붙여주세요..

2023-08-16 09:59 UTC, JunJaBoy reviewed
.

2023-08-16 10:09 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        }
view의 enabled 속성은 안드로이드 네임스페이스 안에 정의되어 있는 속성을 사용합니다

2023-08-16 10:36 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        }
isEnabled = false 이렇게 바꾸어주는 코드가 없어도 될까요?

2023-08-16 11:11 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        }
넵 그렇긴 한데 생각해보니까 안드로이드 네임스페이스를 사용하는 속성들은 클래스 내부에서 따로 작업해줄 필요가 없을 것 같네요..?
ex) android:textAppearance, android:textStyle, android:fontFamiliy..

2023-08-17 02:36 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        }
사실 저도 그런 생각이 조금 들기는 했어요. alpha도 꼭 정해줘야하는지도 조금 궁금했고요

2023-08-17 02:40 UTC, JunJaBoy commented on app/src/main/res/layout/fragment_button.xml
> +    android:padding="12dp"
이건 뭐 뷰 짜는 사람 나름이긴 하지만 개인적으로 padding보다는 내부 태그에 margin을 주는 편이에요. 그림자 같은 속성이 잘리지 않게 하기 위해서 그러는데, padding 설정하고 clipToPadding 속성값을 false로 두는 것보다 더 간편하더라고요.
https://namooplus.tistory.com/11

2023-08-17 02:41 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/InitializableDrawable.kt
접근제한자가 없어요

2023-08-17 11:41 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        }
안드로이드 네임 스페이스를 사용한 속성들은 내부 코드를 제거하는게 좋을까요??
저는 지우긴 해야 할 것 같다는 생각인데 준수님은 어떻게 생각하시나요??..

2023-08-17 11:42 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
> +        }
일단 전 enabled 설정하는 코드는 지워도 된다고 생각해요

2023-08-20 14:21 UTC, JunJaBoy approved these changes

2023-08-20 14:23 UTC, merged