🔀 :: (#13) chip icon chip 구현
team-xquare/xquare-design-system-android pull request #15
Opened 2023-07-27 05:10 UTC by chlgkdms

### 개요
chip components 를 구현했습니다.

### 작업사항
chip layout 구현
chip playground 구현
XChip Custom View 클래스 구현
XChip attribute 구현

### 참고자료
custom view https://lucky516.tistory.com/173

2023-07-27 05:11 UTC, JunJaBoy commented on app/src/main/res/layout/playground_chip.xml
다음에 다른 분들이랑 네이밍 협의하셔야겠네요.. 깃헙 프로젝트에 태스크 남겨주세요

2023-07-27 05:11 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/chip/XChip.kt
> +) {
이 주석 이제 빼죠.. ktlint가 잡는데

2023-07-27 05:55 UTC, chlgkdms commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/chip/XChip.kt
> +) {
수정했습니다.

2023-08-23 06:04 UTC, JunJaBoy commented on app/src/main/res/values/strings.xml
> +    <!--Chip-->
주석 소문자로 적어주세요

2023-08-23 06:06 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
> +        setTextAttrs(attributes.getText(R.styleable.XChip_android_text))
아규먼트로 넣어주는 값 변수로 따로 빼면 가독성이 좋아질 것 같아요

2023-08-23 06:07 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_chip_filled_enabled.xml
> +    android:color="?attr/colorSecondary">
이건 무슨 색상인가요? ripple or solid

2023-08-23 06:07 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_chip_outlined_enabled.xml
> +    android:color="?attr/colorSecondary">
22

2023-08-23 06:07 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/bg_chip_text_enabled.xml
> +    android:color="?attr/colorSecondary">
33

2023-08-23 06:08 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="trailingSrcTint" />
common과 차이점이 있나요?

2023-08-23 06:08 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
여기도요

2023-08-23 06:08 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:textStyle" format="reference" />
여기도 common이랑 중복되는 것 같아요..

2023-08-23 06:08 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +    <declare-styleable name="IconXChip">
네이밍 확인해주세요

2023-08-23 06:09 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/dimens_padding.xml
@Tmdhoon2 여기에 단위 명시 안해도 될까요? 나중에 되면 고정 사이즈도 넣을 가능성 있지 않을까요..?

2023-08-23 06:10 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_chip.xml
> +    </style>
@Tmdhoon2 혹시 버튼 텍스트 컬러는 어디에서 어떻게 제공하나요?

2023-08-23 06:10 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_chip.xml
> +    </style>
\+ 기본 텍스트 컬러는 어떻게 입력되나요?

2023-08-23 06:11 UTC, JunJaBoy reviewed
수고하셨어요~ ktlint 한 번 검사해주시고 커멘트 확인 부탁드립니다.

2023-08-23 06:13 UTC, chlgkdms commented on xquare-design-system-android/src/main/res/drawable/bg_chip_filled_enabled.xml
> +    android:color="?attr/colorSecondary">
ripple 컬러 입니다!

2023-08-23 06:15 UTC, chlgkdms commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="trailingSrcTint" />
common에서 format을 정의해주고 안해주고 차이인데 서로 겹치게 선언해주면 오류가 나서 빼는 수밖에 없었습니다

2023-08-23 06:16 UTC, chlgkdms commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="android:textStyle" format="reference" />
아 그리고 android 붙여준거는 또 다르더라구요 따로 저희가 선언해준 것들만 오류가 나서 android 붙인거 안붙인거 차이도 있습니다

2023-08-23 06:18 UTC, chlgkdms commented on app/src/main/res/values/strings.xml
> +    <!--Chip-->
해결했습니다!

2023-08-23 06:18 UTC, Tmdhoon2 requested changes

2023-08-23 06:18 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/styles_chip.xml
> +    </style>
버튼 텍스트 컬러 같은 경우도 안드로이드 네임스페이스의 textColor 속성 사용해서 지정해주긴 하는데 declared-styleable에 속성 명시를 안해줬네요..

2023-08-23 06:18 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/dimens_padding.xml
그 고정 사이즈라는게 일반 int값 말씀하시는건가요??
근데 어차피 padding은 dp 단위로 주니까 굳이 명시할 필요가 없지 않을까요??... (제가 잘 이해한게 맞다면)

2023-08-23 06:23 UTC, chlgkdms commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
> +        setTextAttrs(attributes.getText(R.styleable.XChip_android_text))
수정했습니다!

2023-08-23 06:24 UTC, chlgkdms commented on xquare-design-system-android/src/main/res/drawable/bg_chip_outlined_enabled.xml
> +    android:color="?attr/colorSecondary">
이거랑 밑에도 다 ripple 컬러입니다

2023-08-23 06:27 UTC, chlgkdms commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +    <declare-styleable name="IconXChip">
수정했습니다!

2023-08-23 07:03 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
> +        }
```suggestion

DrawableCompat.wrap(this@apply).setTint(tint)
        }
```

2023-08-23 07:04 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="trailingSrcTint" />
음.. 그럼 둘 중 하나 선택해야겠네요 @Tmdhoon2

2023-08-23 07:15 UTC, Tmdhoon2 requested changes

2023-08-23 07:15 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/drawable/ic_test_16.xml
이거 아마 ic_test_24 도 있을텐데 이 파일이랑 같이 ic_sample_16, ic_sample_24로 변경해주실 수 있나요??

2023-08-23 07:19 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="trailingSrcTint" />
속성 이름이라도 정의를 해둬야 이 컴포넌트가 어떤 속성들을 지원하는지 알 수 있지 않을까요..?

2023-08-23 07:27 UTC, chlgkdms commented on xquare-design-system-android/src/main/res/drawable/ic_test_16.xml
수정했습니다

2023-08-25 00:40 UTC, chlgkdms commented on app/src/main/res/layout/playground_chip.xml
수정했습니다!

2023-08-28 23:16 UTC, JunJaBoy approved these changes
잘 동작하는지 확인이 필요할 것 같아요. 이미지 몇 장 첨부해주시면 좋겠습니다.

2023-08-29 01:20 UTC, rladmsdh commented on app/src/main/res/layout/fragment_chip.xml
> +        android:layout_margin="12dp"
마진 쓰지 마세요

2023-08-29 02:53 UTC, yeon0821 approved these changes

2023-08-29 05:46 UTC, Tmdhoon2 requested changes

2023-08-29 05:46 UTC, Tmdhoon2 commented on app/src/main/res/layout/fragment_chip.xml
> +                    android:text="Disabled Chip" />
string resource 사용해주세요

2023-08-29 05:50 UTC, chlgkdms commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
> +    private fun setBackground(): Drawable? {
지금 setBackground로 되어있지 않나요?? 예전 파일 보고 계신것같은데

2023-08-29 05:51 UTC, chlgkdms commented on app/src/main/res/layout/fragment_chip.xml
> +                    android:text="Disabled Chip" />
수정했습니다!

2023-08-29 06:07 UTC, chlgkdms commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
> +    private fun setBackground(): Drawable? {
수정했습니다

2023-08-29 06:27 UTC, Tmdhoon2 requested changes

2023-08-29 06:27 UTC, Tmdhoon2 commented on app/src/main/res/layout/fragment_chip.xml
> +                    android:text="@string/playground_chip_outliend" />
여기 string resource 에 오타있네요
"outliend"

2023-08-29 06:27 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
> +}
ktlint 돌리셨나요?

2023-08-29 06:27 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
> +        val textAlign = attributes.getInt(R.styleable.XChip_android_textAlignment, 0)
여기 defValue로 R 클래스 참조할 수 없나요??
ex) R.font.notosans_regular 나 등등

2023-08-29 06:27 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XIconChip.kt
> +        val backgroundSrc: Drawable? = setBackground() ?: AppCompatResources.getDrawable(
XChip은 이 부분 코드에 개행 분리가 따로 없었던 것 같은데 형식 맞춰주세요

2023-08-29 06:27 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XIconChip.kt
> +            this.setBounds(0, 0, srcWidth, srcHeight)
srcWidth -> width, srcHeight -> height 로 통일해주세요

2023-08-29 06:27 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XIconChip.kt
> +            DrawableCompat.wrap(drawable).setTint(srcTint)
srcTint -> tint 로 통일해주세요

2023-08-29 07:18 UTC, Tmdhoon2 requested changes

2023-08-29 07:27 UTC, chlgkdms commented on xquare-design-system-android/src/main/res/drawable/bg_chip_outlined_enabled.xml
> +                android:width="1dp"
수정했습니다!

2023-08-29 07:27 UTC, chlgkdms commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XIconChip.kt
> +            this.setBounds(0, 0, srcWidth, srcHeight)
수정했습니다

2023-08-29 07:27 UTC, chlgkdms commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XIconChip.kt
> +        val backgroundSrc: Drawable? = setBackground() ?: AppCompatResources.getDrawable(
수정했습니다

2023-08-29 07:39 UTC, Tmdhoon2 approved these changes

2023-08-29 07:40 UTC, merged