🔀 :: (#18) dynamic color 버그 수정
team-xquare/xquare-design-system-android pull request #19
Opened 2023-08-07 09:43 UTC by Tmdhoon2

### 개요

android dynamic color를 재정의 했습니다.
### 작업사항

- app theme dynamic colors 상속
- colorBackground 제거

### 참고자료
- dynamic color https://developer.android.com/develop/ui/views/theming/dynamic-colors

2023-08-07 10:48 UTC, JunJaBoy requested changes

2023-08-07 10:48 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values-night/themes.xml
>      <!--primary-->
요런 코드들은 남아있는 이유가 있나요?

2023-08-07 10:48 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/themes.xml
> +        <!--surface-->
마찬가지로 요런게 남아있는 이유가 있나요?

2023-08-07 12:07 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/values-night/themes.xml
>      <!--primary-->
앗 제거하겠습니당

2023-08-08 06:40 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values-night/themes.xml
> +        <item name="colorOnSurface">@color/neutral_100</item>
Surface가 여기에 있는데, 확인해주실 수 있나요?

2023-08-08 06:41 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values-night/themes.xml
> +        <item name="colorOutlineVariant">@color/neutral_variant_30</item>
Outline이 여기에 있네요..

2023-08-08 06:42 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_typography.xml
이거 놓칠 수 있는 부분인데 잘 수정하신 것 같습니다..!

2023-08-08 06:42 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/themes.xml
> +        <item name="colorOutlineVariant">@color/neutral_variant_80</item>
여기도 이렇게 남아있네요

2023-08-08 06:42 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/themes.xml
> +        <item name="colorOnSurface">@color/neutral_0</item>
22222

2023-08-08 07:49 UTC, JunJaBoy approved these changes

2023-08-08 07:52 UTC, yeon0821 approved these changes

2023-08-08 07:57 UTC, merged