🔀 :: (#23) switch 구현
team-xquare/xquare-design-system-android pull request #24
Opened 2023-08-13 01:04 UTC by rladmsdh

2023-08-14 01:06 UTC, Tmdhoon2 requested changes

2023-08-14 01:29 UTC, rladmsdh commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/xswitch/XSwitch.kt
> +class XSwitch : SwitchCompat {
고치겠습니다

2023-08-14 01:29 UTC, rladmsdh commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/xswitch/XSwitch.kt
> +    private fun init(context: Context, attrs: AttributeSet?) {
넵

2023-08-14 01:29 UTC, rladmsdh commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/xswitch/XSwitch.kt
> +        }
그게 좋겠네요

2023-08-14 01:32 UTC, rladmsdh commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/xswitch/XSwitch.kt
> +    private fun init(context: Context, attrs: AttributeSet?) {
근데 그러면 위에 있는 생성자도 똑같이 진행할까요?

2023-08-14 04:28 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/xswitch/XSwitch.kt
> +    private fun init(context: Context, attrs: AttributeSet?) {
아니요 그 파라미터 2개 이상인 함수들만 작업해주시면 될 것 같습니다!

2023-08-14 04:29 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/xswitch/XSwitch.kt
> +    private fun init(context: Context, attrs: AttributeSet?) {
노션에 코드 컨벤션 정리되어 있는거 확인해보시면 좋을 것 같아요!

2023-08-21 13:55 UTC, Tmdhoon2 requested changes

2023-08-21 13:55 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/drawable/switch_thumb_off.xml
> +        android:width="32dp"
이거 dimens_switch 하나 만들어서 switch 사용되는 값들 한 번에 관리하면 좋을 것 같아요

2023-08-21 13:55 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/drawable/switch_thumb_off.xml
> +        android:width="32dp"
+ 여러 곳에서 사용하고 있는 값들만 
ex) 32dp, 2dp

2023-08-22 03:34 UTC, Tmdhoon2 requested changes

2023-08-22 03:34 UTC, Tmdhoon2 commented on app/src/main/res/layout/fragment_switch.xml
> +        android:layout_marginStart="8dp">
여기 그 switch 마다 margin으로 간격 주는 대신에 fragment_button 참고해서 divider 사용해주실 수 있나용??

2023-08-23 08:21 UTC, Tmdhoon2 requested changes

2023-08-23 08:21 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/switch/XSwitch.kt
> +        setAlphaEnabled()
setAlphaEnabled() 내부 구현이 바뀌어서 리베이스 한 번 받으시고 다시 작업해주셔야 할 것 같습니다

2023-08-23 10:29 UTC, Tmdhoon2 requested changes

2023-08-23 10:29 UTC, Tmdhoon2 commented on app/src/main/res/values/strings.xml
> +    <!--Playground-->
여기 주석 소문자로 바꿔주실 수 있나요??

2023-08-23 10:29 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/switch/XSwitch.kt
> +        val isEnabled = attributes.getBoolean(R.styleable.XButton_android_enabled, true)
여기 R.styleable switch 속성 전달해주셔야 할 것 같아요

2023-08-23 10:39 UTC, Tmdhoon2 approved these changes

2023-08-23 10:43 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/drawable/switch_thumb_off.xml
> +        android:height="@dimen/thumb_height" />
요거 switch_thuhmb_width 이런 느낌으로 해주면 어떰? 아님 width_switch_thumb 이렇게 하거나 @Tmdhoon2

2023-08-23 10:44 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/dimens_switch.xml
> +    <dimen name="track_radius">16dp</dimen>
width_switch_thumb 이런 느낌으로 해주면 안되나요?

2023-08-23 10:45 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/style_switch.xml
> +        <item name="android:switchMinWidth">10dp</item>
혹시 10dp로 하신 이유가 있나요?

2023-08-23 10:45 UTC, rladmsdh commented on xquare-design-system-android/src/main/res/drawable/switch_thumb_off.xml
> +        android:height="@dimen/thumb_height" />
네임을 변경하자고?

2023-08-23 10:46 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/style_switch.xml
> +        <item name="android:switchMinWidth">10dp</item>
ds에는 52dp가 최소값인데 10dp로 하면 어떻게 되나요?

2023-08-23 13:05 UTC, rladmsdh commented on xquare-design-system-android/src/main/res/values/style_switch.xml
> +        <item name="android:switchMinWidth">10dp</item>
그냥 아무일도 일어나지 않습니다

2023-08-24 12:20 UTC, JunJaBoy approved these changes

2023-08-24 12:59 UTC, merged