🔀 :: (#3) typography 정의
team-xquare/xquare-design-system-android pull request #4
Opened 2023-07-22 10:38 UTC by Tmdhoon2

typography style.xml 및 style 별 custom view 클래스를 정의했습니다

2023-07-22 12:21 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/Typography.kt
> +abstract class Typography @JvmOverloads constructor(
접근제한자 명시해주세요
```suggestion
public abstract class Typography @JvmOverloads constructor(
```

2023-07-22 12:23 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/Typography.kt
> +        inflater.inflate(R.layout.typography, findViewById(R.id.typography))
라인 분리해주세요

2023-07-22 13:34 UTC, JunJaBoy requested changes

2023-07-22 13:34 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/typography.xml
확인해보니 TextView랑 다를게 없는 것 같네요.. 이 레이아웃이 필요할까요? 그냥 TextView만 사용하면 안되나요?

2023-07-22 13:34 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/attrs.xml
> +        <attr name="textColor" format="reference|color" />
`android:text`, `android:textColor` 사용하면 어떨까요?

2023-07-22 13:34 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/body/BodyLarge.kt
> +    color = R.color.neutral_30,
이 컬러는 어디에서 나온걸까요? 차라리 `on_surface` 컬러를 생성자로 전달해주면 안되나요?

2023-07-22 13:36 UTC, JunJaBoy requested changes
수고하셨습니다. 그런데 스타일별 클래스가 필요할까 고민되네요. 그냥 TextView에 선언한 style 속성만 추가해주면 될 것 같은데, 불필요한 커스텀뷰가 아닐까 싶습니다. 혹시 커스텀 TextView를 만드신 이유가 있을까요?

2023-07-22 15:11 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/Typography.kt
> +abstract class Typography @JvmOverloads constructor(
혹시 명시해야 하는 이유가 있나요?? (컴파일러가 필요없다고 하기도 하고..)

2023-07-22 15:23 UTC, Tmdhoon2 commented
> 수고하셨습니다. 그런데 스타일별 클래스가 필요할까 고민되네요. 그냥 TextView에 선언한 style 속성만 추가해주면 될 것 같은데, 불필요한 커스텀뷰가 아닐까 싶습니다. 혹시 커스텀 TextView를 만드신 이유가 있을까요?

<img width="458" alt="스크린샷 2023-07-23 오전 12 20 04" src="https://github.com/team-xquare/xquare-design-system-android/assets/102812085/54d7790c-90bf-4888-b9b6-c269239bb989">

스타일별 클래스를 만들면 com.xquare.xds~~ 와 같은 방식으로 사용할 수 있어요
매번 style="@style/HeadLineSmall" <- 이런식으로 사용하는게 번거로울 수 있을 것 같다고 판단해서 각각의 style 별로 CustomView 클래스들을 생성해준거에요
(+ xml 태그에 typography 속성이 명시되어 있는게 코드 파악에도 더 쉬운 것 같네요)

2023-07-22 15:24 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/body/BodyLarge.kt
> +    color = R.color.neutral_30,
아 typography 컬러는 팔레트가 아니라 바로 컬러 참조해서 사용하는줄 알았어요 ㅎㅎ..

2023-07-22 16:15 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/Typography.kt
> +    attrs: AttributeSet? = null,
음 아마 R.attrs 에 적용되는 어노테이션 같아용

2023-07-23 01:09 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/Typography.kt
> +abstract class Typography @JvmOverloads constructor(
aar 파일로 변환되면 public 접근제한자가 주황색 글씨로 표시됩니다. 라이브러리 특성상 API들의 접근제한자가 명시되어있으면 라이브러리 외에서 사용할 수 있다는 것을 인지할 수 있는 점에서 구분이 쉬울 것 같아요.
<img width="1213" alt="image" src="https://github.com/team-xquare/xquare-design-system-android/assets/101160207/5dbce0f4-2e24-409b-b922-76231d3f4ca2">

2023-07-23 01:10 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/Typography.kt
> +    attrs: AttributeSet? = null,
혹시 여기에 명시하기 어려운 애너테이션인걸까요?

2023-07-23 01:12 UTC, JunJaBoy commented
> > 수고하셨습니다. 그런데 스타일별 클래스가 필요할까 고민되네요. 그냥 TextView에 선언한 style 속성만 추가해주면 될 것 같은데, 불필요한 커스텀뷰가 아닐까 싶습니다. 혹시 커스텀 TextView를 만드신 이유가 있을까요?
> 
> <img alt="스크린샷 2023-07-23 오전 12 20 04" width="458" src="https://user-images.githubusercontent.com/102812085/255337225-54d7790c-90bf-4888-b9b6-c269239bb989.png">
> 스타일별 클래스를 만들면 com.xquare.xds~~ 와 같은 방식으로 사용할 수 있어요 매번 style="@style/HeadLineSmall" <- 이런식으로 사용하는게 번거로울 수 있을 것 같다고 판단해서 각각의 style 별로 CustomView 클래스들을 생성해준거에요 (+ xml 태그에 typography 속성이 명시되어 있는게 코드 파악에도 더 쉬운 것 같네요)

음.. TextView인데 Typography라고 선언하는게 이상하네요. 승훈님이 작성하신 코드대로라면 TextView <-> Typography가 상호 변환 가능해야할텐데, TextView의 style 속성이 더 올바른 것 같다고 생각합니다.

2023-07-23 08:17 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/Typography.kt
> +    attrs: AttributeSet? = null,
제가 정의한 attrs.xml 파일이랑 AttributeSet 이랑 달라서 명시하기 어려운 듯 합니닷
아마 이름에서 알 수 있듯이 res 파일 인자에 일반 int (0, 1) 등의 값이 들어오지 못하도록 해주는 역할 같아용 (DrawableRes, StringRes 와 같이..)
<img width="545" alt="스크린샷 2023-07-23 오후 5 17 28" src="https://github.com/team-xquare/xquare-design-system-android/assets/102812085/d0e7ce0e-b594-438c-82e5-eb104fa3521a">

2023-07-23 08:27 UTC, Tmdhoon2 commented
> > > 수고하셨습니다. 그런데 스타일별 클래스가 필요할까 고민되네요. 그냥 TextView에 선언한 style 속성만 추가해주면 될 것 같은데, 불필요한 커스텀뷰가 아닐까 싶습니다. 혹시 커스텀 TextView를 만드신 이유가 있을까요?
> > 
> > 
> > <img alt="스크린샷 2023-07-23 오전 12 20 04" width="458" src="https://user-images.githubusercontent.com/102812085/255337225-54d7790c-90bf-4888-b9b6-c269239bb989.png">
> > 스타일별 클래스를 만들면 com.xquare.xds~~ 와 같은 방식으로 사용할 수 있어요 매번 style="@style/HeadLineSmall" <- 이런식으로 사용하는게 번거로울 수 있을 것 같다고 판단해서 각각의 style 별로 CustomView 클래스들을 생성해준거에요 (+ xml 태그에 typography 속성이 명시되어 있는게 코드 파악에도 더 쉬운 것 같네요)
> 
> 음.. TextView인데 Typography 이름을 선언하는것이 어색하네요.
> 
> * 승훈님이 작성하신 코드대로라면 원래 TextView <-> Typography가 상호 변환 가능한 개념이었다는 느낌이 들어요
> * 같은 결과를 보여주는 두 타이포그래피 정의방법때문에 무조건 혼동이 올 것 같습니다
>   
>   * 누구는 꼭 태그로 타이포그래피를 정의하고, 누구는 style로 타이포그래피를 정의하는 상황이 생길 것 같습니다
>   * 그렇다고 이걸 꼭 하나만 쓰자는 컨벤션으로 정의하기에는 부적절하네요
> 
> TextView의 style 속성만 사용하는 것이 더 올바른 것 같다고 생각합니다. 만약 제 의견 수용하신다면 기존 class들 삭제마시고 `@Deprecated` 애너테이션 추가해주세요.
> 
> * DMS 디자인 시스템을 생각하시면서 코드를 작성하신 것 같다는 조심스런 추측을 해보았는데, 애초에 DMS 타이포그래피도 불필요한 보일러플레이트코드가 너무 많았습니다
>   
>   * 이전에는 modifier 파라미터를 기본 사양으로 지원하지 않아서, 추후 작업하면서 추가했던 기억이 있습니다
> * Material 디자인시스템의 타이포그래피를 선언할 때도 태그 이름으로 선언하지 않습니다
> 
> 혹시 타이포그래피 클래스를 정의하면서 참고하신 자료가 있으면 공유해주세요. 승훈님 작업하신 내용 정말 존중하지만, 아무리 생각해도 동일한 결과값을 내는 두 개의 코드를 관리하는게 번거로울 것 같고, 커스텀 뷰로 정의할 부분이 아닌데 정의하신 것 같다는 생각이 듭니다. 많이 날카롭게 말씀드린 점 죄송합니다. 제 뜻이 잘 전달되었으면 하네요.

사실 처음 작업할 때 많이 고민하고, style 속성으로 지정하는게 맞을지 아니면 예전 DMS 디자인 시스템처럼 이름에 명시해주는게 맞을지 헷갈렸습니다. xml 로 디자인 시스템은 처음 작업하는것이기도 하고, 위 코멘트 어딘가에서도 말씀드렸듯이 CustomLayout 을 구성하는 예제들만 있었거든요 (제가 찾을땐) 그래서 DMS 방식을 따라가야겠다 하고 작업한 것 같아요.! 이 부분은 준수님 의견대로 style 속성으로 지정해주는게 맞다는 생각이 드네요

2023-07-23 13:23 UTC, JunJaBoy commented on xquare-design-system-android/src/main/kotlin/com/xquare/xds/typography/headline/HeadlineMedium.kt
> +)
더이상 안 쓰일 것 같기는 하지만, 요런곳에는 컬러도 정의가 되어있지 않네요..

2023-07-23 13:35 UTC, JunJaBoy requested changes

2023-07-23 13:35 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/layout/typography.xml
> +    android:id="@+id/typography"
```suggestion
<!--{@deprecated Use style attribute of textview instead.}-->
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/typography"
```

2023-07-23 13:35 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values-night/themes.xml
>      <color name="on_surface">@color/neutral_90</color>
여기 수정 부탁드립니다

2023-07-23 13:35 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/styles_typography.xml
> +        <item name="android:lineSpacingExtra">8dp</item>
이 속성은 왜 모두 각기각색인가요?

2023-07-23 13:35 UTC, JunJaBoy commented on xquare-design-system-android/src/main/res/values/themes.xml
> +    <color name="on_background">@color/neutral_0</color>
여기 확인 부탁드립니다

2023-07-23 13:43 UTC, Tmdhoon2 commented on xquare-design-system-android/src/main/res/layout/typography.xml
> +    android:id="@+id/typography"
xml 문서는 첫 번째 라인부터 선언되어야 한다고 해서 두 번째 줄에 추가하겠습니당
<img width="433" alt="스크린샷 2023-07-23 오후 10 43 10" src="https://github.com/team-xquare/xquare-design-system-android/assets/102812085/d6aaf609-ec1d-4f4a-ae1b-db96d0e1b034">

2023-07-23 14:23 UTC, merged